@baseUrl = http://localhost:8080

### Iniciar preparo do item
PATCH {{baseUrl}}/cozinha/itens/7/iniciar-preparo

### Listar itens pendentes
GET {{baseUrl}}/cozinha/itens-em-preparo

### Marcar item como pronto
PATCH {{baseUrl}}/cozinha/itens/7/marcar-pronto

### Entregar o item
PATCH {{baseUrl}}/cozinha/itens/7/entregar

